spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zealot
    username: root
    password: 12345678

mybatis:
  mapper-locations: com.cxf.bootzealot.mapper/*.xml
  type-aliases-package: com.cxf.batishelper.model
