spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zealot
    xxxxxxx: xxxxxxxx
    xxxxxxx: xxxxxxxx

mybatis:
  mapper-locations: com.cxf.bootzealot.mapper/*.xml
  type-aliases-package: com.cxf.batishelper.model
