spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batis-helper
    username: root
    password: 12345678

mybatis:
  mapper-locations: com.cxf.data.mapper/*.xml
  type-aliases-package: com.cxf.data.model

logging:
  level:
    #    root: debug
    com.cxf.data.mapper: debug
    org.springframework.jdbc.datasource: debug
